<?php 
session_start();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Recovery - Personal Finance Tracker</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <style>
        body {
            font-family: 'Raleway', sans-serif;
            background: linear-gradient(135deg, #f5f7fa 0%, #eef2f7 100%);
            margin: 0;
            padding: 0;
            overflow-x: hidden;
        }

        /* Navbar Styles */
        .navbar {
            background-color: #2C3E50;
            padding: 15px 20px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            border-radius: 0 0 10px 10px;
            margin-bottom: 0 !important;
        }

        .navbar .navbar-brand {
            color: white;
            font-weight: bold;
            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.3);
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .logo-icon {
            font-size: 24px;
        }

        /* Main Content */
        .main-content {
            padding: 10px 20px;
            max-width: 1200px;
            margin: 0 auto;
        }

        /* Card Design */
        .card {
            border-radius: 15px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            border: none;
            margin-bottom: 20px;
            background-color: white;
            position: relative;
            z-index: 1;
            transition: transform 0.3s ease;
        }

        .card:hover {
            transform: translateY(-5px);
        }

        .card-header {
            background-color: #2C3E50;
            color: white;
            border-bottom: none;
            padding: 20px;
            border-radius: 15px 15px 0 0 !important;
        }

        .card-body {
            padding: 30px;
        }

        /* Form Styles */
        .form-control {
            border-radius: 10px;
            border: 1px solid #ddd;
            transition: border-color 0.3s ease;
            padding: 12px 15px;
        }

        .form-control:focus {
            border-color: #1ABC9C;
            box-shadow: none;
        }

        .btn-primary {
            background-color: #E74C3C;
            border-color: #E74C3C;
            border-radius: 30px;
            transition: all 0.3s ease;
            font-weight: bold;
            padding: 12px 25px;
            font-size: 16px;
        }

        .btn-primary:hover {
            background-color: #C0392B;
            transform: translateY(-2px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
        }

        /* Animation */
        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .animated {
            animation: fadeIn 1s ease-in-out;
        }

        /* Background Animation */
        .background-animation {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            overflow: hidden;
        }
    </style>
</head>
<body>
    <!-- Background Animation -->
    <div class="background-animation" id="backgroundAnimation">
        <!-- Particles will be generated by JavaScript -->
    </div>

    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand" href="#">
                <span class="logo-icon">💰</span>
                Personal Finance Tracker
            </a>
        </div>
    </nav>

    <div class="main-content animated">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header text-center">
                        <h4>Recover Password</h4>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST">
                            <div class="form-group">
                                <label for="email">E-Mail Address</label>
                                <input type="email" id="email" class="form-control" name="email" required autofocus>
                            </div>
                            <button type="submit" name="recover" class="btn btn-primary btn-block">Recover</button>
                        </form>
                        <?php
                        if (isset($_POST["recover"])) {
                            include('connect/connection.php');  // Ensure this file has correct DB credentials

                            $email = mysqli_real_escape_string($connect, $_POST["email"]);

                            $sql = mysqli_query($connect, "SELECT * FROM login WHERE email='$email'");
                            $fetch = mysqli_fetch_assoc($sql);

                            if (mysqli_num_rows($sql) == 0) {
                                echo "<div class='alert alert-danger'>Sorry, no account found with that email.</div>";
                            } elseif ($fetch["status"] == 0) {
                                echo "<div class='alert alert-warning'>Your account needs to be verified before recovering the password.</div>";
                                echo "<script>window.location.replace('index.php');</script>";
                            } else {
                                // Generate a secure token
                                $token = bin2hex(random_bytes(50));

                                // Store token in session (or database)
                                $_SESSION['token'] = $token;
                                $_SESSION['email'] = $email;

                                // Send Email with PHPMailer
                                require "Mail/phpmailer/PHPMailerAutoload.php";
                                $mail = new PHPMailer(true);

                                try {
                                    $mail->isSMTP();
                                    $mail->Host = 'smtp.gmail.com';
                                    $mail->SMTPAuth = true;
                                    $mail->Username = '210490131017.sneh@gmail.com';  // Your email
                                    $mail->Password = 'txra pvhh pzwf fpzu';  // Use an App Password instead of the actual password
                                    $mail->SMTPSecure = 'tls';  // Change to 'ssl' if port is 465
                                    $mail->Port = 587;  // Use 465 for SSL

                                    $mail->setFrom('210490131017.sneh@gmail.com', 'Password Reset');
                                    $mail->addAddress($email);

                                    $mail->isHTML(true);
                                    $mail->Subject = "Recover Your Password";
                                    $mail->Body = "
                                        <p><strong>Dear User,</strong></p>
                                        <p>We received a request to reset your password.</p>
                                        <p>Click the link below to reset your password:</p>
                                        <p><a href='http://localhost/pft/reset_psw.php?token=$token'>Reset Password</a></p>
                                        <p>If you did not request this, please ignore this email.</p>
                                        <br>
                                        <p>Regards,<br><strong>Personal Finance Tracker (PFT)</strong></p>";

                                    $mail->send();
                                    echo "<div class='alert alert-success'>Password recovery link has been sent to your email.</div>";
                                } catch (Exception $e) {
                                    echo "<div class='alert alert-danger'>Mailer Error: " . $mail->ErrorInfo . "</div>";
                                }
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Create background particles
        document.addEventListener('DOMContentLoaded', function() {
            const container = document.getElementById('backgroundAnimation');
            const particleCount = 100;

            for (let i = 0; i < particleCount; i++) {
                const particle = document.createElement('div');
                particle.classList.add('particle');
                
                // Random size between 1px and 9px
                const size = Math.random() * 8 + 1;
                particle.style.width = `${size}px`;
                particle.style.height = `${size}px`;
                
                // Random position
                particle.style.left = `${Math.random() * 100}%`;
                particle.style.top = `${Math.random() * 100}%`;
                
                // Random animation duration between 15s and 25s
                particle.style.animationDuration = `${Math.random() * 10 + 15}s`;
                
                // Random animation delay
                particle.style.animationDelay = `${Math.random() * 10}s`;
                
                container.appendChild(particle);
            }
        });
    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</body>
</html>